services:
  nexe_bridge:
    build:
      context: .
      no_cache: true
    container_name: nexe_bridge
    restart: unless-stopped
    user: "0"
    command:
      - '-stats=false'
      - '-nexellia=host.docker.internal:33455'
    ports:
      - 5555:5555
      - 2114:2114
    extra_hosts:
      - host.docker.internal:host-gateway
